includes:
  - "$RUNNING_NG_PACKAGE_DATA/base/minheap.yml"

benchmarks:
  dacapobach:
    - avrora
    - fop
    - jython
    - luindex
    - pmd
    - sunflow
    - xalan

configs:
  - "adoptopenjdk-11|ms|s|c2|g1"
